### ISSUE TITLE
Create entities models with the database operaions

### ISSUE THREAD

**Issue by Aldokimi** [Mohido/Characters-Relations-Grapher#11]
In the API service, models for entities need to be created, the process of creation is as follows:

- Create an interface for the model.
- Create a model Scheme, where we can call this scheme to create a new model object and save it to the database.
- Create the data pre-creation functions (e.g.: password check function, data validators, etc...)

after we have our model Schema ready we can create a model typescript object that can be used everywhere else.

**Comment by Mohido** [comment]
Canceled Plan. No SaaS will be implemented for this project
